version: '3'

services:
  aio-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aio-server
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=info
      - API_VERSION=v1
      - ALLOWED_ORIGINS=["*"]
    restart: unless-stopped 